In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [6]:
type(iris)

sklearn.utils.Bunch

In [7]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
X = iris.data

In [9]:
y = iris.target

In [10]:
# class 0--->[1,0,0]
# class 0--->[0,1,0]
# class 0--->[0,0,1]

In [11]:
from keras.utils import to_categorical

In [12]:
y = to_categorical(y)

In [13]:
y.shape

(150, 3)

In [14]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
np.array([5,19,15,20])/20

array([0.25, 0.95, 0.75, 1.  ])

In [40]:
scaler_object = MinMaxScaler()

In [41]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [49]:
scaled_X_train = scaler_object.transform(X_train)
len(scaled_X_train)

100

In [48]:
len(y_train)

100

In [50]:
scaled_X_test = scaler_object.transform(X_test)

In [51]:
from keras.models import Sequential
from keras.layers import Dense


In [53]:
model =Sequential()
model.add(Dense(8,input_dim = 4, activation = 'relu'))
model.add(Dense(8,input_dim = 4, activation = 'relu'))
model.add(Dense(3,input_dim = 4, activation = 'softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [54]:
model.fit(scaled_X_train, y_train, epochs = 150, verbose = 2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 1s - loss: 1.0850 - acc: 0.0300
Epoch 2/150
 - 0s - loss: 1.0786 - acc: 0.1100
Epoch 3/150
 - 0s - loss: 1.0730 - acc: 0.2400
Epoch 4/150
 - 0s - loss: 1.0673 - acc: 0.3500
Epoch 5/150
 - 0s - loss: 1.0615 - acc: 0.4600
Epoch 6/150
 - 0s - loss: 1.0556 - acc: 0.5300
Epoch 7/150
 - 0s - loss: 1.0500 - acc: 0.5700
Epoch 8/150
 - 0s - loss: 1.0442 - acc: 0.6600
Epoch 9/150
 - 0s - loss: 1.0386 - acc: 0.6800
Epoch 10/150
 - 0s - loss: 1.0331 - acc: 0.7000
Epoch 11/150
 - 0s - loss: 1.0275 - acc: 0.7200
Epoch 12/150
 - 0s - loss: 1.0219 - acc: 0.7200
Epoch 13/150
 - 0s - loss: 1.0162 - acc: 0.7300
Epoch 14/150
 - 0s - loss: 1.0104 - acc: 0.7100
Epoch 15/150
 - 0s - loss: 1.0045 - acc: 0.7000
Epoch 16/150
 - 0s - loss: 0.9987 - acc: 0.7000
Epoch 17/150
 - 0s - loss: 0.9929 - acc: 0.7200
Epoch 18/150
 - 0s - loss: 0.9868 - acc: 0.7300
Epoch 19/150
 - 0s - loss: 0.9808 - acc: 0.7200
Epoch 20/150
 - 0s - loss: 0.9745 - acc: 0.7100
E

In [56]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [57]:
predictions = model.predict_classes(scaled_X_test)

In [58]:
y_test.argmax(axis = 1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [59]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [60]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 16]], dtype=int64)

In [61]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

   micro avg       0.98      0.98      0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [62]:
accuracy_score(y_test.argmax(axis=1), predictions)

0.98

In [63]:
model.save('myfirstmodel.h5')

In [64]:
from keras.models import load_model

In [65]:
new_model = load_model('myfirstmodel.h5')

In [66]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [67]:
##LSTM